### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mary-grace**
As you may have seen via email this morning, we (SparkPost) adjusted our service plans today. TL;DR: all paid plans now include full-service support, and we launched a new free developer account option. We are discontinuing the 100k/month free program which you mentioned in your README. Would you mind making the change? Thanks!

### CODE REVIEW

**Comment by mary-grace** [comment]
I'm not sure what you mean... it's already submitted as a PR: https://github.com/djagya/yii2-sparkpost/pull/15

Is there something else you need me to do?

**Comment by djagya** [comment]
@mary-grace oh, sorry! Was reviewing forks and somehow missed that it was already merged.
Thanks again 👍

**Comment by mary-grace** [comment]
all good :) I don't think it's been merged yet tho... it still looks like it's open to me. I can't merge it because I don't have write access. Can you merge it for me please?

**Comment by djagya** [comment]
My bad, sorry for not merging so long :)

**Comment by mary-grace** [comment]
all good! thanks for pushing it through :)

**Pull request merged**
